const langRu = {
  "main-title": "Добро пожаловать в AI Bridge!",
  "main-desc": "Это вводный курс по ИИ.",
  "main-goal": "Цели",
  "main-g1": "Понять ИИ",
  "main-g2": "Зачем компании используют ИИ",
  "main-g3": "Попробовать код",

  "ch1-title": "Глава 1: ИИ",
  "ch1-q1": "Что такое ИИ?",
  "ch1-a1": "ИИ — искусственный интеллект.",
  "ch1-key1": "ИИ не думает, а вычисляет.",
  "ch1-q2": "Правила vs ИИ",
  "ch1-rule": "Правила",
  "ch1-ai": "ИИ",
  "ch1-p1": "Человек задаёт правила",
  "ch1-p2": "ИИ учится по данным",
  "ch1-q3": "Слабый vs сильный",
  "ch1-p3": "Сейчас только слабый ИИ",
  "ch1-p4": "Сильного ИИ нет",

  "ch1-ml-dl-title": "ML vs DL",
  "ch1-ml-desc": "Обучение на данных",
  "ch1-dl-desc": "Глубокое обучение",
  "ch1-dl-li1": "Нужно больше данных",

  "ch1-turing-title": "Тест Тьюринга",
  "ch1-turing-p1": "Может ли машина думать?",
  "ch1-turing-test": "Если нельзя отличить от человека",

  "ch1-eliza-title": "ELIZA",
  "ch1-eliza-p1": "Первый чат-бот",
  "ch1-eliza-effect": "Эффект ELIZA",

  "ch1-history-title": "История ИИ",
  "ch1-history-p1": "Бумы и кризисы",
  "hist-1": "ELIZA",
  "hist-2": "Экспертные системы",
  "hist-3": "Глубокое обучение",

  "ch1-exp-title": "Попробуйте ИИ",
  "ch1-exp-desc": "Нажмите кнопку",

  "ch2-title": "Глава 2: Бизнес",
  "ch2-q1": "Почему ИИ?",
  "ch2-v1": "Снижение затрат",
  "ch2-v2": "Скорость",
  "ch2-v3": "Прогноз",
  "ch2-p1": "ИИ помогает экономить",
  "ch2-q2": "Примеры",
  "ch2-c1": "YouTube",
  "ch2-c2": "Amazon",
  "ch2-c3": "Naver",
  "ch2-c4": "Tesla",
  "hist-period-1": "1-й бум (1950–60)",
  "hist-period-2": "2-й бум (1980)",
  "hist-period-3": "3-й бум (настоящее время)",

  "ch2-q3": "Наши инструменты: Python и Colab",
  "ch2-p2": "Мы используем Python — самый популярный язык, и Google Colab, который не требует установки.",

  "ch3-eval-title": "Насколько умный ИИ?",
  "ch2-job-title": "Профессии",
  "job1-name": "Data Scientist",
  "job1-task": "Анализ",
  "job2-name": "AI Engineer",
  "job2-task": "Модели",
  "job3-name": "Data Engineer",
  "job3-task": "Данные",
  "job4-name": "AI Planner",
  "job4-task": "Планирование",

  "ch3-title": "Глава 3: ML",
  "ch3-ml-q": "Что такое ML?",
  "ch3-ml-def": "Обучение по данным",
  "ch3-ml-desc": "Компьютер учится",
  "ch3-types-title": "Типы",
  "ch3-supervised": "С учителем",
  "ch3-sup-desc": "Есть ответ",
  "ch3-clf": "Классификация",
  "ch3-reg": "Регрессия",
  "ch3-unsupervised": "Без учителя",
  "ch3-unsup-desc": "Нет ответа",
  "ch3-reinforce": "Обучение с наградой",
  "ch3-rei-desc": "Награда",

  "ch3-fitting-title": "Недообучение vs Переобучение",
  "underfit": "Недообучение",
  "under-desc": "Слишком просто",
  "overfit": "Переобучение",
  "over-desc": "Запоминает",

  "ch3-eval-title": "Оценка",
  "ch3-acc": "Точность",
  "ch3-matrix": "Матрица ошибок"
};