const langEn = {
  "main-title": "Welcome to AI Bridge!",
  "main-desc": "This site is an introductory AI learning guide for international students. Let's learn AI through images and hands-on activities without complex formulas!",
  "main-goal": "Today's Goals",
  "main-g1": "Understand what AI is",
  "main-g2": "Learn why companies use AI",
  "main-g3": "Try AI code yourself",

  "ch1-title": "Chapter 1: Understanding AI (Week 2)",
  "ch1-q1": "What is AI?",
  "ch1-a1": "AI stands for Artificial Intelligence. It refers to intelligence created by humans in machines.",
  "ch1-key1": "AI does not think like humans; it calculates patterns!",
  "ch1-q2": "Rule-Based Systems vs AI",
  "ch1-rule": "Rule-Based System",
  "ch1-ai": "AI",
  "ch1-p1": "Rule-based systems: Humans create the rules directly.",
  "ch1-p2": "AI: Computers find rules and patterns by analyzing data.",
  "ch1-q3": "Weak AI vs Strong AI",
  "ch1-p3": "All AI we use today is Weak AI.",
  "ch1-p4": "Strong AI does not exist yet.",

  "ch1-ml-dl-title": "1. ML vs DL",
  "ch1-ml-desc": "<b>Machine Learning:</b> Learns patterns from data.",
  "ch1-dl-desc": "<b>Deep Learning:</b> Brain-like learning system.",
  "ch1-dl-li1": "Needs more data and GPU.",

  "ch1-turing-title": "2. Turing Test",
  "ch1-turing-p1": "Can machines think?",
  "ch1-turing-test": "If humans cannot distinguish machine vs human → AI.",

  "ch1-eliza-title": "3. ELIZA",
  "ch1-eliza-p1": "First chatbot (1966).",
  "ch1-eliza-effect": "People felt emotional connection → ELIZA Effect.",

  "ch1-history-title": "4. AI History",
  "ch1-history-p1": "Boom and Winter cycles.",
  "hist-1": "ELIZA appeared",
  "hist-2": "Expert systems",
  "hist-3": "Deep learning success",
  "hist-period-1": "1st Boom (1950–60)",
  "hist-period-2": "2nd Boom (1980)",
  "hist-period-3": "3rd Boom (Present)",

  "ch1-exp-title": "5. Try AI",
  "ch1-exp-desc": "Click below to try AI",

  "ch2-title": "Chapter 2: AI in Business",
  "ch2-q1": "Why do companies use AI?",
  "ch2-v1": "Cost Reduction",
  "ch2-v2": "Speed",
  "ch2-v3": "Prediction",
  "ch2-p1": "Companies use AI to save money and predict future.",
  "ch2-q2": "Examples",
  "ch2-c1": "YouTube: recommendation",
  "ch2-c2": "Amazon: logistics",
  "ch2-c3": "Naver: translation",
  "ch2-c4": "Tesla: autonomous driving",

  "ch2-job-title": "AI Jobs",
  "job1-name": "Data Scientist",
  "job1-task": "Analyze data",
  "job2-name": "AI Engineer",
  "job2-task": "Build models",
  "job3-name": "Data Engineer",
  "job3-task": "Prepare data",
  "job4-name": "AI Planner",
  "job4-task": "Plan AI services",
  "ch2-q3": "Our Tools: Python & Colab",
  "ch2-p2": "We use Python, the most popular language, and Google Colab, which requires no installation.",

  "ch3-title": "Chapter 3: Machine Learning",
  "ch3-ml-q": "What is ML?",
  "ch3-ml-def": "Learning from data",
  "ch3-ml-desc": "Computer learns patterns",
  "ch3-types-title": "Types of ML",
  "ch3-supervised": "Supervised",
  "ch3-sup-desc": "Data + answer",
  "ch3-clf": "Classification",
  "ch3-reg": "Regression",
  "ch3-unsupervised": "Unsupervised",
  "ch3-unsup-desc": "No answer",
  "ch3-reinforce": "Reinforcement",
  "ch3-rei-desc": "Reward system",
  "ch3-eval-title": "How Smart is AI?",

  "ch3-fitting-title": "Underfitting vs Overfitting",
  "underfit": "Underfitting",
  "under-desc": "Too simple",
  "overfit": "Overfitting",
  "over-desc": "Too memorized",

  "ch3-eval-title": "Evaluation",
  "ch3-acc": "Accuracy",
  "ch3-matrix": "Confusion Matrix"
};